version: "3.4"

services:
  node:
    build:
      context: .
      target: app_node
    environment:
      NODE_OPTIONS: '--openssl-legacy-provider'
      HOST: '0.0.0.0'
    command: yarn start --host 0.0.0.0
    volumes:
      - .:/srv/app
      - ./node_modules:/srv/app/node_modules
    ports:
      - ${HTTP_PORT:-80}:3000
    stdin_open: true
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
